/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.javaproject;

import static com.mycompany.javaproject.AddBook.isNumeric;
import static com.mycompany.javaproject.AddBook.isAlphaNumeric;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.NumberFormat;
import java.time.Instant;
import javax.swing.JOptionPane;

/**
 *
 * @author ennis
 */
public class AddSupplies extends javax.swing.JFrame {

    /**
     * Creates new form AddSupplies
     */
    public AddSupplies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        supplies_title = new javax.swing.JLabel();
        supplies_title_field = new javax.swing.JTextField();
        supplies_type_field = new javax.swing.JComboBox<>();
        supplies_type_label = new javax.swing.JLabel();
        supplies_price_label = new javax.swing.JLabel();
        supplies_price_field = new javax.swing.JTextField();
        make_label = new javax.swing.JLabel();
        supplies_make_field = new javax.swing.JTextField();
        model_label = new javax.swing.JLabel();
        supplies_model_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplies_description_field = new javax.swing.JTextArea();
        description_label = new javax.swing.JLabel();
        submit_supplies_button = new javax.swing.JButton();
        supplies_condition_label = new javax.swing.JLabel();
        supplies_condition_field = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Georgia Pro Cond", 0, 36)); // NOI18N
        jLabel1.setText("Add Supplies");

        supplies_title.setText("Title");

        supplies_type_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arts and Crafts", "Electronics", "Writing", "Backpacks and Bags", "Folders and Papers", "Basic School Supplies" }));

        supplies_type_label.setText("Type");

        supplies_price_label.setText("Price");

        make_label.setText("Make");

        model_label.setText("Model");

        supplies_description_field.setColumns(20);
        supplies_description_field.setRows(5);
        jScrollPane1.setViewportView(supplies_description_field);

        description_label.setText("Product Description");

        submit_supplies_button.setText("Submit");
        submit_supplies_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_supplies_buttonMouseClicked(evt);
            }
        });

        supplies_condition_label.setText("Condition");

        supplies_condition_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New (Never been used)", "Good", "Fair", "Poor" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(supplies_type_label)
                                .addComponent(supplies_title)
                                .addComponent(supplies_type_field, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(supplies_price_field, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(supplies_make_field)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(make_label)
                                                .addGap(146, 146, 146)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(supplies_price_label)
                                            .addGap(148, 148, 148)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(supplies_condition_label)
                                        .addComponent(model_label)
                                        .addComponent(supplies_model_field, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(1, 1, 1)))
                            .addComponent(supplies_title_field, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(description_label)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(supplies_condition_field, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(submit_supplies_button, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(supplies_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplies_title_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplies_type_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(supplies_type_field, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(make_label)
                    .addComponent(model_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplies_make_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplies_model_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplies_price_label)
                    .addComponent(supplies_condition_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supplies_condition_field, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(supplies_price_field))
                .addGap(18, 18, 18)
                .addComponent(description_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submit_supplies_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_supplies_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_supplies_buttonMouseClicked
        // Handle submit for supplies
        String supplies_description = supplies_description_field.getText().trim();
        String title = supplies_title_field.getText().trim();
        String price = supplies_price_field.getText().trim();
        String supplies_type = (String)supplies_type_field.getSelectedItem();
        String supplies_condition = (String)supplies_condition_field.getSelectedItem();
        String make = supplies_make_field.getText().trim();
        String model = supplies_model_field.getText().trim();
        
        // Basic input validation
        if(supplies_description.isEmpty() || supplies_description.isEmpty() || title.isEmpty() || price.isEmpty() || make.isEmpty()) {
            // Error message for failed validation
            JOptionPane.showMessageDialog(this, "Please ensure that you fill in all required (*) fields.");
        } else {
            // proceed if all fields are filled in
            // additional validation
            if(!isAlphaNumeric(title) || !isAlphaNumeric(make)){
                JOptionPane.showMessageDialog(this, "The title and make fields should contain only letters and numbers.");
            } else {
                if(!isNumeric(price)){
                    JOptionPane.showMessageDialog(this, "The price field should contain numeric value.");
                } else {
                    try {
                        //get information about current user
                        FileManager getFiles = new FileManager();
                        String userdata = getFiles.current_user();
                        String current_user_email = getFiles.current_user_email();
                        String supplies_directory = getFiles.get_supplies_directory();

                        NumberFormat currency_format = NumberFormat.getCurrencyInstance();
                        String currency = currency_format.format(Double.parseDouble(price));

                        Instant timestamp = Instant.now();   

                        if(model.isEmpty())
                            model = "N/A";

                        // Define the file to be and save it as the user's email + item title address
                        File myObj = new File(supplies_directory + current_user_email + " - " + title + ".txt");

                        if (myObj.createNewFile()) {
                            System.out.println("File created: " + myObj.getName());
                            try {
                                // Write the data to the file, one value on each line
                                FileWriter myWriter = new FileWriter(myObj);
                                myWriter.write("     Title: \t\t" + title + "\n" 
                                               + "Type: \t\t" + supplies_type + "\n" 
                                               + "Make: \t\t" + make + "\n"  
                                               + "Model: \t\t" + model + "\n" 
                                               + "Condition: \t" + supplies_condition + "\n"
                                               + "Price: \t\t" + currency + "\n"
                                               + "Posted By: \t" + userdata + "\n"
                                               + "Posted On: \t" + timestamp.toString());

                                // file description
                                myWriter.write("\nDescription:\n" + supplies_description);

                                // close file
                                myWriter.close();

                                // Display confirmation message to the user and then dispose of the window
                                JOptionPane.showMessageDialog(this, "Your item has been added to our collection.");
                                this.dispose();
                            } catch (IOException e) {
                                // Catch any errors that may be thrown
                                System.out.println("An error occurred. Please report this to an administrator.");
                                e.printStackTrace();
                            }
                        } else {
                            // Display message if the email address already exists
                            JOptionPane.showMessageDialog(this, "You already have a item with that title listed.");
                        }
                    } catch (IOException e) {
                        // Catch/DIsplay error messages
                        JOptionPane.showMessageDialog(this, "You have already added an item with that title.");
                        e.printStackTrace();
                    }
                }
            }
        }
    }//GEN-LAST:event_submit_supplies_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupplies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel make_label;
    private javax.swing.JLabel model_label;
    private javax.swing.JButton submit_supplies_button;
    private javax.swing.JComboBox<String> supplies_condition_field;
    private javax.swing.JLabel supplies_condition_label;
    private javax.swing.JTextArea supplies_description_field;
    private javax.swing.JTextField supplies_make_field;
    private javax.swing.JTextField supplies_model_field;
    private javax.swing.JTextField supplies_price_field;
    private javax.swing.JLabel supplies_price_label;
    private javax.swing.JLabel supplies_title;
    private javax.swing.JTextField supplies_title_field;
    private javax.swing.JComboBox<String> supplies_type_field;
    private javax.swing.JLabel supplies_type_label;
    // End of variables declaration//GEN-END:variables
}
