/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.javaproject;

import java.io.BufferedReader;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ennis
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        email_address_label = new javax.swing.JLabel();
        email_address_field = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        signin_button = new javax.swing.JButton();
        create_account_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign Into Your Account");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Georgia Pro Cond", 0, 36)); // NOI18N
        jLabel1.setText("Sign Into Your Account");

        email_address_label.setText("Email Address");

        password_label.setText("Password:");

        signin_button.setText("Sign In");
        signin_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signin_buttonMouseClicked(evt);
            }
        });

        create_account_button.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        create_account_button.setText("Create an Account");
        create_account_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_account_buttonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Click here if you do not have an account.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(password_field)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(create_account_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(signin_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password_label, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_address_field)
                    .addComponent(email_address_label, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(email_address_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email_address_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_account_button)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signin_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_buttonMouseClicked
        // Executed when the Signin button is clicked
        String email_address = email_address_field.getText().trim();
        String password = password_field.getText().trim();
        boolean fileFound = false;
        
        if(email_address.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill enter an email address and password.");
        } else {

            // creates the directory if it doesn't already exists. prevents an error from being thrown
            new File("C:/handmedown/users").mkdirs();
            
            // check the specified directory
            File directory = new File("C:/handmedown/users");
            
            // define the filename we are searching for
            String filename = email_address + ".txt";
            
            // find and store the files in the directory in a File array
            File[] listOfFiles = directory.listFiles();
            BufferedReader reader = null;
            try {
                reader = new BufferedReader(new FileReader(directory + "/" +  filename));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            for (File file : listOfFiles) {
                if (file.isFile()) {
                    
                    if (file.getName().endsWith(filename)) {
                        fileFound = true;
                        break;
                    }
                }
            }
            
            if(fileFound == false) {
                JOptionPane.showMessageDialog(null, "An account does not exist with that email address.");
            } else {
                // if the file is found, read the contents and see if the password matches
                try {
                    reader = new BufferedReader(new FileReader(directory + "/" + filename));
                    String line = reader.readLine();
                    boolean password_found = false;
                    int increment = 0;

                    while (line != null && increment < 3) {
                            String email = line;
                            // read next line
                            line = reader.readLine();
                            // check if the line's value matches the password entered
                            if (line.equals(password)) {
                                password_found = true;
                            }
                            increment++;
                    } // end while loop

                    // if the passwords match, log the user into the system
                    if (password_found == true){
                        JOptionPane.showMessageDialog(null, "Success. You are now logged in.");

                        this.setVisible(false);
                        new MainWindow().setVisible(false);
                        new Dashboard().setVisible(true);
                        
                        //create temporary directory for the currently active user
                        new File("C:/handmedown/activeuser").mkdirs();
                        File temp_storage = new File("C:/handmedown/activeuser");

                        // Deletes the data for any other temporay user that previously used the system
                        File[] temp_files = temp_storage.listFiles();
                        for (File myFile: temp_files) {
                            if (myFile.isDirectory()) {  
                                deleteDir(myFile);
                            } 
                            myFile.delete();
                        }
                        
                        try {
                            // create the temporary file
                            File myObj = new File("C:/handmedown/activeuser/" + email_address + ".txt");
                            // Write the data to the file, one value on each line
                            FileWriter myWriter = new FileWriter(myObj);
                            myWriter.write(email_address);
                            myWriter.close();

                        } catch (IOException e) {
                            // Catch any errors that may be thrown
                            System.out.println("An error occurred. Could not create temporary storage directory for active user.");
                            e.printStackTrace();
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Password incorrect, please try again.");
                    }

                    reader.close();
                } catch (IOException e) {
                        e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_signin_buttonMouseClicked

    private void create_account_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_account_buttonMouseClicked
        // Handle click event for the create account button
        this.setVisible(false);
        new Signup().setVisible(true);
    }//GEN-LAST:event_create_account_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }
    
    public void deleteDir(File dir) {
        File[] files = dir.listFiles();

        for (File myFile: files) {
            if (myFile.isDirectory()) {  
                deleteDir(myFile);
            } 
            myFile.delete();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_account_button;
    private javax.swing.JTextField email_address_field;
    private javax.swing.JLabel email_address_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_label;
    private javax.swing.JButton signin_button;
    // End of variables declaration//GEN-END:variables
}
